openapi: "3.0.0"
info:
  title: LaLigaTracker API
  version: "1.0.0"
paths:
  /api/matches:
    get:
      summary: Obtener todos los partidos
      responses:
        '200':
          description: Lista de partidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
    post:
      summary: Crear un nuevo partido
      requestBody:
        description: Datos del partido a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Match'
      responses:
        '200':
          description: Partido creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
  /api/matches/{id}:
    get:
      summary: Obtener un partido por ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Partido encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '404':
          description: Partido no encontrado
    put:
      summary: Actualizar un partido
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        description: Datos del partido a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Match'
      responses:
        '200':
          description: Partido actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '404':
          description: Partido no encontrado
    delete:
      summary: Eliminar un partido
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Partido eliminado
        '404':
          description: Partido no encontrado

  /api/matches/{id}/goal:
    patch:
      summary: Registrar un gol
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Gol registrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '404':
          description: Partido no encontrado

  /api/matches/{id}/yellowcard:
    patch:
      summary: Registrar una tarjeta amarilla
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Tarjeta amarilla registrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '404':
          description: Partido no encontrado

  /api/matches/{id}/redcard:
    patch:
      summary: Registrar una tarjeta roja
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Tarjeta roja registrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '404':
          description: Partido no encontrado

  /api/matches/{id}/extratime:
    patch:
      summary: Registrar tiempo extra
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Tiempo extra activado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
        '404':
          description: Partido no encontrado

components:
  schemas:
    Match:
      type: object
      properties:
        id:
          type: integer
        equipoLocal:
          type: string
        equipoVisitante:
          type: string
        fecha:
          type: string
          example: "03/27/2025"
        goals:
          type: integer
        yellowCards:
          type: integer
        redCards:
          type: integer
        extraTime:
          type: boolean
